#! /bin/sh

# 程序启动
$HOME/.config/bspwm/autostart.sh
xsetroot -cursor_name left_ptr
#################################
#       Global Settings
# 所有布尔值默认为false，除非特殊说明
#################################
# BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#42A5F5"
bspc config presel_feedback_color	"#5e81ac"
# 如果桌面树中只有一个平铺窗口，那么将桌面布局设置为单片窗口
bspc config single_monocle       true
# 默认分割比率
bspc config split_ratio          0.50
# 为单片桌面布局移除平铺窗口的边框。
bspc config borderless_monocle   true
# 为单片桌面布局移除平铺窗口的缝隙。
bspc config gapless_monocle      false
# 悬浮窗口 Winodows键 + 
# - 左键：移动窗口
# - 右键：调整窗口大小，整体
# - 中键：调整窗口大小，单边
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#################################
#   Monitor and Desktop Settings
#################################
# 在显示器或桌面四周增加的填充空间。
bspc config top_padding          50
bspc config bottom_padding       6
bspc config left_padding         6
bspc config right_padding        6
# 分隔窗口间的间隙
bspc config window_gap           6
# 窗口边框宽度
bspc config border_width         2


# Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8


# 全屏窗口应用列表
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen


# 浮动窗口应用列表
bspc rule -a Arandr state=floating
bspc rule -a fcitx5-config-qt state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a qt5ct state=floating
bspc rule -a feh state=floating
bspc rule -a Toolkit state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Thunar state=floating follow=on

# 平铺窗口应用列表
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

# 指定应用到特定的工作区
bspc rule -a Alacritty desktop=^1 follow=on
bspc rule -a firefox desktop=^2
bspc rule -a Code desktop=^3
#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

 # change the desktop number here
 FLOATING_DESKTOP_ID=$(bspc query -D -d '^6')

 bspc subscribe node_add | while read -a msg ; do
    desk_id=${msg[2]}
    wid=${msg[4]}
    [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
 done


###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window